#!/usr/bin/env bash
set -euo pipefail

USER_HOME=$(eval echo $USER)
DOTFILES="/home/$USER_HOME/dotfiles"
HOSTNAME=$(hostname)

# Run nixos-generate-config command
sudo nixos-generate-config --show-hardware-config > "$DOTFILES/modules/hardware-configuration.nix" || { echo "Failed to generate hardware configuration"; exit 1; }

# navigate to the dotfiles dir
cd "$DOTFILES" || { echo "Failed to cd to $DOTFILES"; exit 1; }

# Rebuild NixOS configuration
sudo nixos-rebuild switch --flake .#$HOSTNAME || { echo "Failed to rebuild NixOS configuration"; exit 1; }

echo "Rebuild completed successfully."

read -rp "Do you want to commit these changes? (y/n) " answer

if [[ "$answer" =~ ^[Yy]$ ]]; then
  git add .
  git commit
fi
