#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    # don't pipe to sort, this way we get existing sessions at the front
    selected=$((tmux ls | awk -F':' '{print $1}'; find ~/stripe ~/personal -mindepth 1 -maxdepth 1 -type d) | uniq | fzf --print-query | awk 'END {print}')
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)
dir_option=""

# check if the selected directory exists, omit the -c parameter if it dose
if [[ -d $selected ]]; then
    dir_option="-c $selected"
fi

# If tmux is not running and we are not inside an existing tmux session,
# start a new tmux session with the name and directory based on the selection.
if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -n $selected_name $dir_option
    exit 0
fi

# If a tmux session with the selected name does not already exist,
# create a new detached tmux session with the selected name and directory.    
if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -n $selected_name $dir_option
fi

tmux switch-client -t $selected_name
