/* Generated by Omarchy from the active theme. */
:root,
body,
.sk-client-theme--dark,
.sk-client-theme--light,
.sk-client-theme--light-inverted-sidebar,
.p-client,
.p-client_workspace,
.p-client_workspace_wrapper,
.p-ia4_client,
.p-ia4_client_container {
  color-scheme: {{ mode }} !important;

  --sk_primary_foreground: {{ foreground_rgb }} !important;
  --sk_primary_background: {{ background_rgb }} !important;
  --sk_inverted_foreground: {{ background_rgb }} !important;
  --sk_inverted_background: {{ foreground_rgb }} !important;
  --sk_foreground_max: {{ foreground_rgb }} !important;
  --sk_foreground_high: {{ foreground_rgb }} !important;
  --sk_foreground_low: {{ muted_rgb }} !important;
  --sk_highlight: {{ accent_rgb }} !important;
  --sk_highlight_hover: {{ bright_blue_rgb }} !important;
  --sk_highlight_accent: {{ accent_rgb }} !important;
  --sk_secondary_highlight: {{ yellow_rgb }} !important;

  /* Slack's workspace theme has a separate set of legacy sidebar tokens. */
  --sk_sidebar_bg: {{ dark_background_rgb }} !important;
  --sk_sidebar_text: {{ foreground_rgb }} !important;
  --sk_sidebar_muted_text: {{ muted_rgb }} !important;
  --sk_sidebar_hover_bg: {{ selection_rgb }} !important;
  --sk_sidebar_active_item: {{ accent_rgb }} !important;
  --sk_sidebar_active_item_text: {{ darker_background_rgb }} !important;
  --sk_sidebar_top_nav_bg: {{ darker_background_rgb }} !important;

  --dt_color-base-pry: {{ background }} !important;
  --dt_color-base-sec: {{ dark_background }} !important;
  --dt_color-base-ter: {{ lighter_background }} !important;
  --dt_color-base-modal: {{ darker_background }}e6 !important;
  --dt_color-content-pry: {{ foreground }} !important;
  --dt_color-content-sec: {{ light_foreground }} !important;
  --dt_color-content-ter: {{ muted }} !important;
  --dt_color-content-hgl-1: {{ accent }} !important;
  --dt_color-content-hgl-2: {{ green }} !important;
  --dt_color-content-hgl-3: {{ yellow }} !important;
  --dt_color-content-imp: {{ red }} !important;
  --dt_color-surf-pry: {{ foreground }}0f !important;
  --dt_color-surf-sec: {{ foreground }}29 !important;
  --dt_color-surf-hgl-1: {{ accent }}40 !important;
  --dt_color-otl-pry: {{ muted }} !important;
  --dt_color-otl-sec: {{ muted }}80 !important;
  --dt_color-otl-ter: {{ muted }}4d !important;
  --dt_color-ctr-pry: {{ lighter_background }} !important;
  --dt_color-ctr-sec: {{ dark_background }} !important;

  /* Newer Slack releases resolve workspace sidebar colors through the green
     palette selected by the workspace theme. Redirect every green family to
     the active Omarchy accent ramp so a saved Slack theme cannot win. */
  --dt_color-plt-grass-0: {{ darker_background_rgb }} !important;
  --dt_color-plt-grass-5: {{ dark_background_rgb }} !important;
  --dt_color-plt-grass-10: {{ background_rgb }} !important;
  --dt_color-plt-grass-20: {{ lighter_background_rgb }} !important;
  --dt_color-plt-grass-30: {{ selection_rgb }} !important;
  --dt_color-plt-grass-40: {{ muted_rgb }} !important;
  --dt_color-plt-grass-50: {{ accent_rgb }} !important;
  --dt_color-plt-grass-60: {{ accent_rgb }} !important;
  --dt_color-plt-grass-70: {{ bright_blue_rgb }} !important;
  --dt_color-plt-grass-80: {{ light_foreground_rgb }} !important;
  --dt_color-plt-grass-90: {{ foreground_rgb }} !important;
  --dt_color-plt-grass-100: {{ bright_foreground_rgb }} !important;

  --dt_color-plt-cilantro-0: {{ darker_background_rgb }} !important;
  --dt_color-plt-cilantro-5: {{ dark_background_rgb }} !important;
  --dt_color-plt-cilantro-10: {{ background_rgb }} !important;
  --dt_color-plt-cilantro-20: {{ lighter_background_rgb }} !important;
  --dt_color-plt-cilantro-30: {{ selection_rgb }} !important;
  --dt_color-plt-cilantro-40: {{ muted_rgb }} !important;
  --dt_color-plt-cilantro-50: {{ accent_rgb }} !important;
  --dt_color-plt-cilantro-60: {{ accent_rgb }} !important;
  --dt_color-plt-cilantro-70: {{ bright_blue_rgb }} !important;
  --dt_color-plt-cilantro-80: {{ light_foreground_rgb }} !important;
  --dt_color-plt-cilantro-90: {{ foreground_rgb }} !important;
  --dt_color-plt-cilantro-100: {{ bright_foreground_rgb }} !important;

  --dt_color-plt-mojito-0: {{ darker_background_rgb }} !important;
  --dt_color-plt-mojito-5: {{ dark_background_rgb }} !important;
  --dt_color-plt-mojito-10: {{ background_rgb }} !important;
  --dt_color-plt-mojito-20: {{ lighter_background_rgb }} !important;
  --dt_color-plt-mojito-30: {{ selection_rgb }} !important;
  --dt_color-plt-mojito-40: {{ muted_rgb }} !important;
  --dt_color-plt-mojito-50: {{ accent_rgb }} !important;
  --dt_color-plt-mojito-60: {{ accent_rgb }} !important;
  --dt_color-plt-mojito-70: {{ bright_blue_rgb }} !important;
  --dt_color-plt-mojito-80: {{ light_foreground_rgb }} !important;
  --dt_color-plt-mojito-90: {{ foreground_rgb }} !important;
  --dt_color-plt-mojito-100: {{ bright_foreground_rgb }} !important;

  --dt_color-plt-jade-0: {{ darker_background_rgb }} !important;
  --dt_color-plt-jade-5: {{ dark_background_rgb }} !important;
  --dt_color-plt-jade-10: {{ background_rgb }} !important;
  --dt_color-plt-jade-20: {{ lighter_background_rgb }} !important;
  --dt_color-plt-jade-30: {{ selection_rgb }} !important;
  --dt_color-plt-jade-40: {{ muted_rgb }} !important;
  --dt_color-plt-jade-50: {{ accent_rgb }} !important;
  --dt_color-plt-jade-60: {{ accent_rgb }} !important;
  --dt_color-plt-jade-70: {{ bright_blue_rgb }} !important;
  --dt_color-plt-jade-80: {{ light_foreground_rgb }} !important;
  --dt_color-plt-jade-90: {{ foreground_rgb }} !important;
  --dt_color-plt-jade-100: {{ bright_foreground_rgb }} !important;
}
