/* Generated by Omarchy from the active theme. Loaded by Millennium. */
:root {
  color-scheme: {{ mode }} !important;
  accent-color: {{ accent }} !important;

  --omarchy-steam-bg: {{ background }};
  --omarchy-steam-bg-dark: {{ dark_background }};
  --omarchy-steam-bg-darker: {{ darker_background }};
  --omarchy-steam-bg-light: {{ lighter_background }};
  --omarchy-steam-selection: {{ selection }};
  --omarchy-steam-fg: {{ foreground }};
  --omarchy-steam-fg-soft: {{ light_foreground }};
  --omarchy-steam-muted: {{ muted }};
  --omarchy-steam-accent: {{ accent }};
  --omarchy-steam-accent-bright: {{ bright_blue }};
  --omarchy-steam-danger: {{ red }};
  --omarchy-steam-success: {{ green }};

  /* Steam-owned variables that currently have stable semantic names. */
  --main-text-color: {{ foreground }} !important;
  --main-light-blue-background: {{ accent }} !important;
  --main-text-on-light-blue: {{ darker_background }} !important;
  --main-top-image-bg: {{ darker_background }} !important;
  --main-editor-bg-color: {{ dark_background }} !important;
  --main-editor-input-bg-color: {{ lighter_background }} !important;
  --main-editor-text-color: {{ foreground }} !important;
  --main-editor-section-title-color: {{ light_foreground }} !important;
  --menu-background: {{ dark_background }} !important;
  --virtualmenu-accent: {{ accent }} !important;
  --virtualmenu-bg: {{ dark_background }} !important;
  --virtualmenu-bg-hover: {{ selection }} !important;
  --virtualmenu-fg: {{ foreground }} !important;
}

html.MillenniumWindow_MainSteamWindow,
html.MillenniumWindow_FriendsList,
html.MillenniumWindow_FriendChatWindow,
html.MillenniumWindow_Settings,
html.MillenniumWindow_GameProperties,
html.MillenniumWindow_ContextMenu,
html.MillenniumWindow_MainSteamWindow body,
html.MillenniumWindow_FriendsList body,
html.MillenniumWindow_FriendChatWindow body,
html.MillenniumWindow_Settings body,
html.MillenniumWindow_GameProperties body,
html.MillenniumWindow_ContextMenu body,
.DesktopUI,
.friendsui-container {
  background-color: var(--omarchy-steam-bg-darker) !important;
  color: var(--omarchy-steam-fg) !important;
}

/* Steam's Library uses CSS-module identifiers rather than useful color
   variables. These are the narrowest current selectors for its structural
   surfaces; keeping them here avoids flattening game artwork and thumbnails. */
body.DesktopUI div._1ENHEsrSLcTRtPQFl1F-wL {
  background: var(--omarchy-steam-bg) !important;
  color: var(--omarchy-steam-fg) !important;
}

body.DesktopUI div._3Z7VQ1IMk4E3HsHvrkLNgo,
body.DesktopUI div._1_yS5UP7el0aN4vntx3dx {
  background: var(--omarchy-steam-bg-darker) !important;
  color: var(--omarchy-steam-fg) !important;
}

body.DesktopUI div._3x1HklzyDs4TEjACrRO2tB,
body.DesktopUI div._1ijTaXJJA5YWl_fW2IxcaT {
  background: var(--omarchy-steam-bg-dark) !important;
  color: var(--omarchy-steam-fg) !important;
}

body.DesktopUI div._1rDh5rXSFZJOqCa4UpnI4z,
body.DesktopUI div._3xRRJfD2xy95i9NhJxLTp0,
body.DesktopUI div._3xRRJfD2xy95i9NhJxLTp0 div._2gSXCB6PbOlMxslr8hm6dm,
body.DesktopUI div._3xRRJfD2xy95i9NhJxLTp0 div._3Sb2o_mQ30IDRh0C72QUUu,
body.DesktopUI div._3xRRJfD2xy95i9NhJxLTp0 div._2Dd4T78PcCTUVgOtDGFY5j {
  background: var(--omarchy-steam-bg) !important;
  color: var(--omarchy-steam-fg) !important;
}

body.DesktopUI div._3xRRJfD2xy95i9NhJxLTp0 div._17uEBe5Ri8TMsnfELvs8-N,
body.DesktopUI div._2gZXhRmKUk68pA28-5ZmGQ {
  background: var(--omarchy-steam-bg-light) !important;
  color: var(--omarchy-steam-fg) !important;
}

body.DesktopUI div.Jbe--NUNw7sxbxGsMSjVa {
  background: var(--omarchy-steam-bg) !important;
  color: var(--omarchy-steam-fg) !important;
}

body.DesktopUI div._20QAC4WMXm8qFE8waUT5oo {
  background: var(--omarchy-steam-bg-light) !important;
  color: var(--omarchy-steam-fg) !important;
}

body.DesktopUI div._7AlhCx3XGzBeIrQaCneUD._1gqEjB5QsKT_NftD1dEsdZ
  div._19axKcqYRuaJ8vdYKYmtTQ {
  color: var(--omarchy-steam-accent) !important;
}

body.DesktopUI div._2-O4ZG0KrnSrzISHBKctFQ.sXMOsx8OIRalBMxO9yFY5,
body.DesktopUI div._2-O4ZG0KrnSrzISHBKctFQ._1UBpAXP408Ez_L_mXhW5Q9,
body.DesktopUI div._1UBpAXP408Ez_L_mXhW5Q9 > div._2-O4ZG0KrnSrzISHBKctFQ {
  background: var(--omarchy-steam-selection) !important;
  color: var(--omarchy-steam-fg) !important;
}

body.DesktopUI svg.f6-7-5CWFxNqF2BycKWlb > circle {
  stroke: var(--omarchy-steam-accent) !important;
}

html.client_chat_frame body,
html.web_chat_frame body,
div.chatDialogs,
div.chatWindow,
div.chatWindow div.chatHeader {
  background: var(--omarchy-steam-bg) !important;
  color: var(--omarchy-steam-fg) !important;
}

div.chatRoomGroupNavColumn,
div.MemberListColumn,
div.chatWindow div.chatEntry {
  background: var(--omarchy-steam-bg-dark) !important;
  color: var(--omarchy-steam-fg) !important;
}

.DialogContent,
.DialogContentTransition,
.DesktopUI .DialogContent,
.friendsui-container .DialogContent {
  background: var(--omarchy-steam-bg) !important;
  color: var(--omarchy-steam-fg) !important;
}

.DialogTextInputBase,
._DialogInputContainer,
.DesktopUI .DialogTextInputBase,
.friendsui-container .DialogTextInputBase {
  background: var(--omarchy-steam-bg-light) !important;
  color: var(--omarchy-steam-fg) !important;
  border-color: var(--omarchy-steam-muted) !important;
}

button.DialogButton {
  background: var(--omarchy-steam-bg-light) !important;
  color: var(--omarchy-steam-fg) !important;
}

button.DialogButton:hover,
button.DialogButton.gpfocus,
.DesktopUI .title-area-icon:hover,
.friendsui-container .title-area-icon:hover {
  background: var(--omarchy-steam-selection) !important;
  color: var(--omarchy-steam-fg) !important;
}

button.DialogButton.Primary,
.DialogToggleField_Option.Active,
.DialogSlider_Value,
.DialogProgressBar_Value {
  background: var(--omarchy-steam-accent) !important;
  color: var(--omarchy-steam-bg-darker) !important;
}

button.DialogButton.GreenPlay,
button.DialogButton.GreenPlay:hover,
button.DialogButton.GreenPlay.gpfocus {
  background: var(--omarchy-steam-success) !important;
  color: var(--omarchy-steam-bg-darker) !important;
}

.DesktopUI .title-area-icon.closeButton:hover,
.friendsui-container .title-area-icon.closeButton:hover {
  background: var(--omarchy-steam-danger) !important;
}

::selection {
  background: var(--omarchy-steam-selection) !important;
  color: var(--omarchy-steam-fg) !important;
}

::-webkit-scrollbar-thumb {
  background-color: var(--omarchy-steam-muted) !important;
}

::-webkit-scrollbar-thumb:hover {
  background-color: var(--omarchy-steam-accent) !important;
}
