/* Generated by Omarchy from the active theme. */
:root {
  color-scheme: {{ mode }} !important;

  --WDS-accent: {{ accent }} !important;
  --WDS-accent-RGB: {{ accent_rgb }} !important;
  --WDS-accent-emphasized: {{ bright_blue }} !important;
  --WDS-accent-emphasized-RGB: {{ bright_blue_rgb }} !important;
  --WDS-accent-deemphasized: {{ selection }} !important;
  --WDS-accent-deemphasized-RGB: {{ selection_rgb }} !important;

  --WDS-app-wash: {{ darker_background }} !important;
  --WDS-app-wash-RGB: {{ darker_background_rgb }} !important;
  --WDS-background-wash-plain: {{ background }} !important;
  --WDS-background-wash-plain-RGB: {{ background_rgb }} !important;
  --WDS-background-wash-inset: {{ dark_background }} !important;
  --WDS-background-wash-inset-RGB: {{ dark_background_rgb }} !important;
  --WDS-background-elevated-wash-plain: {{ lighter_background }} !important;
  --WDS-background-elevated-wash-plain-RGB: {{ lighter_background_rgb }} !important;

  --WDS-surface-default: {{ background }} !important;
  --WDS-surface-default-RGB: {{ background_rgb }} !important;
  --WDS-surface-emphasized: {{ lighter_background }} !important;
  --WDS-surface-emphasized-RGB: {{ lighter_background_rgb }} !important;
  --WDS-surface-elevated-default: {{ dark_background }} !important;
  --WDS-surface-elevated-default-RGB: {{ dark_background_rgb }} !important;
  --WDS-surface-elevated-emphasized: {{ lighter_background }} !important;
  --WDS-surface-elevated-emphasized-RGB: {{ lighter_background_rgb }} !important;
  --WDS-surface-inverse: {{ foreground }} !important;
  --WDS-surface-inverse-RGB: {{ foreground_rgb }} !important;
  --WDS-surface-highlight: rgba({{ foreground_rgb }}, 0.10) !important;
  --WDS-surface-highlight-RGB: {{ foreground_rgb }} !important;
  --WDS-surface-pressed: rgba({{ foreground_rgb }}, 0.18) !important;
  --WDS-surface-pressed-RGB: {{ foreground_rgb }} !important;

  --WDS-content-default: {{ foreground }} !important;
  --WDS-content-default-RGB: {{ foreground_rgb }} !important;
  --WDS-content-action-default: {{ foreground }} !important;
  --WDS-content-action-default-RGB: {{ foreground_rgb }} !important;
  --WDS-content-deemphasized: {{ light_foreground }} !important;
  --WDS-content-deemphasized-RGB: {{ light_foreground_rgb }} !important;
  --WDS-content-disabled: {{ muted }} !important;
  --WDS-content-disabled-RGB: {{ muted_rgb }} !important;
  --WDS-content-inverse: {{ background }} !important;
  --WDS-content-inverse-RGB: {{ background_rgb }} !important;
  --WDS-content-on-accent: {{ darker_background }} !important;
  --WDS-content-on-accent-RGB: {{ darker_background_rgb }} !important;
  --WDS-content-read: {{ blue }} !important;
  --WDS-content-read-RGB: {{ blue_rgb }} !important;
  --WDS-content-external-link: {{ accent }} !important;
  --WDS-content-external-link-RGB: {{ accent_rgb }} !important;
  --WDS-content-action-emphasized: {{ accent }} !important;
  --WDS-content-action-emphasized-RGB: {{ accent_rgb }} !important;

  --WDS-lines-outline-default: {{ muted }} !important;
  --WDS-lines-outline-default-RGB: {{ muted_rgb }} !important;
  --WDS-lines-divider: rgba({{ foreground_rgb }}, 0.10) !important;
  --WDS-lines-divider-RGB: {{ foreground_rgb }} !important;
  --WDS-components-surface-nav-bar: {{ dark_background }} !important;
  --WDS-components-surface-nav-bar-RGB: {{ dark_background_rgb }} !important;
  --WDS-components-active-list-row: rgba({{ foreground_rgb }}, 0.10) !important;
  --WDS-components-active-list-row-RGB: {{ foreground_rgb }} !important;
  --WDS-components-filter-surface-selected: {{ selection }} !important;
  --WDS-components-filter-surface-selected-RGB: {{ selection_rgb }} !important;

  --WDS-persistent-always-branded: {{ accent }} !important;
  --WDS-persistent-always-branded-RGB: {{ accent_rgb }} !important;
  --WDS-persistent-activity-indicator: {{ green }} !important;
  --WDS-persistent-activity-indicator-RGB: {{ green_rgb }} !important;
  --WDS-secondary-positive: {{ green }} !important;
  --WDS-secondary-positive-RGB: {{ green_rgb }} !important;
  --WDS-secondary-negative: {{ red }} !important;
  --WDS-secondary-negative-RGB: {{ red_rgb }} !important;
  --WDS-secondary-warning: {{ yellow }} !important;
  --WDS-secondary-warning-RGB: {{ yellow_rgb }} !important;

  --WDS-systems-bubble-surface-incoming: {{ lighter_background }} !important;
  --WDS-systems-bubble-surface-incoming-RGB: {{ lighter_background_rgb }} !important;
  --WDS-systems-bubble-surface-outgoing: {{ selection }} !important;
  --WDS-systems-bubble-surface-outgoing-RGB: {{ selection_rgb }} !important;
  --WDS-systems-bubble-surface-system: {{ dark_background }} !important;
  --WDS-systems-bubble-surface-system-RGB: {{ dark_background_rgb }} !important;
  --WDS-systems-chat-background-wallpaper: {{ darker_background }} !important;
  --WDS-systems-chat-background-wallpaper-RGB: {{ darker_background_rgb }} !important;
  --WDS-systems-chat-surface-composer: {{ lighter_background }} !important;
  --WDS-systems-chat-surface-composer-RGB: {{ lighter_background_rgb }} !important;
  --WDS-systems-chat-surface-tray: {{ background }} !important;
  --WDS-systems-chat-surface-tray-RGB: {{ background_rgb }} !important;
  --WDS-systems-status-seen: {{ accent }} !important;
  --WDS-systems-status-seen-RGB: {{ accent_rgb }} !important;
}
