[general]
import = [
    # uncomment the flavour you want below:
    # "~/.config/alacritty/catppuccin-latte.toml"
    # "~/.config/alacritty/catppuccin-frappe.toml",
    # "~/.config/alacritty/catppuccin-macchiato.toml",
    "~/.config/alacritty/catppuccin-mocha.toml",
]
[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "None"

opacity = 0.93
blur = true

[colors]
transparent_background_colors = true

[keyboard]
bindings = [
    # binds command-# to M-1, which is interpreted in our tmux.conf
    # to switch the active window
    # { key = "Key1", mods = "Command", chars = "\u001b1" },
    # { key = "Key2", mods = "Command", chars = "\u001b2" },
    # { key = "Key3", mods = "Command", chars = "\u001b3" },
    # { key = "Key4", mods = "Command", chars = "\u001b4" },
    # { key = "Key5", mods = "Command", chars = "\u001b5" },
    { key = "Key0", mods = "Control", chars = "\u001b[48;5u" },
    { key = "Key1", mods = "Control", chars = "\u001b[49;5u" },
    { key = "Key2", mods = "Control", chars = "\u001b[50;5u" },
    { key = "Key3", mods = "Control", chars = "\u001b[51;5u" },
    { key = "Key4", mods = "Control", chars = "\u001b[52;5u" },
    { key = "Key5", mods = "Control", chars = "\u001b[53;5u" },
    { key = "Key6", mods = "Control", chars = "\u001b[54;5u" },
    { key = "Key7", mods = "Control", chars = "\u001b[55;5u" },
    { key = "Key8", mods = "Control", chars = "\u001b[56;5u" },
    { key = "Key9", mods = "Control", chars = "\u001b[57;5u" },
]

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 16

[selection]
save_to_clipboard = true

[terminal]
osc52 = "CopyPaste"
